image: go1.4
git:
  path: github.com/cpalone/githubbot
script:
  - go get
  - go build
notify:
  webhook:
    urls:
      - http://172.31.38.240:8082/dronehook
    on_started: true
    on_success: true
    on_failure: true
